url: http://blog.youxu.info
name: 4G Spaces
description: Eric Xu, PhD (徐宥) Software engineer, certified personal trainer and calligraphier. AI, martial arts, musicals and Zen. Ex-Googler, tech lead manager at Fitbit. @mathena
